### ISSUE TITLE
#suggestion

### ISSUE THREAD

**Issue by 3d0n1** [NYAN-x-CAT/Lime-Loader#2]
do you have any  code that after execute  copy itself to another path then delete first execute file?

**Comment by NYAN-x-CAT** [comment]
I was going to add these stuff tomorrow, you have to wait bro.

**Comment by NYAN-x-CAT** [comment]
https://github.com/NYAN-x-CAT/Lime-Loader/blob/master/Lime-Dropper-1/Lime-Dropper-1/Program.cs#L70
