### ISSUE TITLE
New Tools

### ISSUE THREAD

**Issue by londonerain** [NYAN-x-CAT/Lime-Loader#3]
first thank you for the excellent tools!
I have a question do you have any plan to build dropper or something like that for minergate or open source xmrig? I see that you had previously built miners for example drop miners with persistence, melt and hidden options or runpe etc.

**Comment by londonerain** [comment]
here is one for example https://github.com/DylanAlloy/MinerDropper

**Comment by NYAN-x-CAT** [comment]
No sorry
